#Runs low pass example with equation specified in file.
runLowPassExample:
	rm -f figures/lowpassFigure.png
	rm -f figures/amplitudeSpectrum.png
	rm -f figures/amplitudeSpectrumOfFilteredSignal.png
	rm -f figures/logAmplitudeSpectrum.png
	rm -f figures/logAmplitudeSpectrumOfFilteredSignal.png
	python3 lowpassEx.py

