#Runs low pass example with equation specified in file.
runLowPassExample:
	rm -f figures/lowpassFigure.png
	rm -f figures/lowpassFigureDownsampled.png
	rm -f figures/ampSpectrum.png
	rm -f figures/ampSpectrumDownsampled.png
	rm -f figures/logAmpSpectrum.png
	rm -f figures/logAmpSpectrumDownsampled.png
	python3 lowpassEx.py

